In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [39]:
def bin2dec(binary):
    if binary=="00":
        dec=0
    elif binary=="01":
        dec=1
    elif binary=="10":
        dec=2
    else:
        dec=3
    
    return dec

In [40]:
bin2dec("10")

2

In [3]:
def dec2bin(decimal):
  if decimal==0:
    binary='00'
  elif decimal==1:
    binary='01'
  elif decimal==2:
    binary='10'
  else:
    binary='11'
  return binary


In [4]:
dec2bin(3)

'11'

In [5]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [6]:
#sigmoid(3)

In [7]:
#Now, The derivative function of sigmoid is 
#sigmoid(x)*(1-sigmoid(x))
#So,we define a function called sigmoid_derivative as it will be used
#in backprop

In [8]:
def sigmoid_derivative(x):
    return sigmoid(x)*(1-sigmoid(x))

In [9]:
def softmax(X):
    expX=np.exp(X)
    return expX/(expX.sum(axis=1,keepdims=True))

In [10]:
#softmax([[3,3],[1,0]])

In [11]:
#So, we need to define our feature set for calculating
#the output.
#Now there should be 3 inputs for each calculation
#There are 4 possibilities(0,1,2,3) for 1st and 2nd input
#and 2 possibilities for the 3rd(0,1)
#So,there are 4*4*2=32 types of features/combinations

In [12]:
#We need to give labels as we are building a supervised machine
#learning model

In [13]:
features=[(0,0,0), (0,1,0), (0,2,0), (0,3,0),
              (1,0,0), (1,1,0), (1,2,0), (1,3,0),
               (2,0,0), (2,1,0), (2,2,0), (2,3,0),
               (3,0,0), (3,1,0), (3,2,0), (3,3,0),
               
               (0,0,1), (0,1,1), (0,2,1), (0,3,1),
              (1,0,1), (1,1,1), (1,2,1), (1,3,1),
               (2,0,1), (2,1,1), (2,2,1), (2,3,1),
               (3,0,1), (3,1,1), (3,2,1), (3,3,1)
              ] 

labels=[0, 1, 2, 3,
            1, 0, 3, 2,
             2, 3, 0, 1,
             3, 2, 1, 0,
             
             3, 2, 1, 0,
             2, 3, 0, 1,
             1, 0, 3, 2,
             0, 1, 2, 3
            ]

In [14]:
features=np.array(features)

cont_labels=np.zeros((32,4))

In [15]:
len(labels)

32

In [16]:
features.shape

(32, 3)

In [17]:
for i in range(len(labels)):
    cont_labels[i,labels[i]]=1

In [18]:
cont_labels

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
features.shape[0]

32

In [20]:
features.shape[1]

3

In [21]:
n=features.shape[0]
inputs=features.shape[1]

hidden_neurons=25
output_neurons=4

wgh=np.random.rand(inputs,hidden_neurons)
bh=np.random.rand(hidden_neurons)
#Random initialisation of weights and bias of hidden gate

wgo=np.random.rand(hidden_neurons,output_neurons)
bo=np.random.rand(output_neurons)
#Random initialisation of weights and bias of output gate

alpha=10e-4
#alpha is the learning rate

In [22]:
n

32

In [23]:
inputs

3

In [24]:
wgh

array([[0.99208804, 0.85231212, 0.17265768, 0.00419737, 0.2873631 ,
        0.20435494, 0.17858703, 0.80728499, 0.77966201, 0.53940527,
        0.52474531, 0.46619789, 0.30219244, 0.40547077, 0.90657939,
        0.00149714, 0.94093659, 0.00330588, 0.53832071, 0.17340997,
        0.03016696, 0.10320311, 0.36980704, 0.28213651, 0.95289805],
       [0.5742927 , 0.57621947, 0.87022734, 0.93585444, 0.50116132,
        0.77897504, 0.79552067, 0.55928866, 0.20899596, 0.48321877,
        0.31076133, 0.50483218, 0.3531137 , 0.17317659, 0.37068444,
        0.19139462, 0.64664275, 0.91212431, 0.38734696, 0.33381719,
        0.56482188, 0.65247941, 0.09268593, 0.45065797, 0.96467991],
       [0.65621387, 0.97785815, 0.90538372, 0.91963011, 0.62348022,
        0.82233242, 0.4894187 , 0.94424041, 0.83023374, 0.29639635,
        0.05122293, 0.56204161, 0.72624567, 0.35101886, 0.5733443 ,
        0.82015926, 0.29208899, 0.31500071, 0.30654649, 0.8644139 ,
        0.30030024, 0.38070327, 0.10394635, 0.

In [25]:
bh

array([0.57364681, 0.49825783, 0.84461648, 0.17112072, 0.23544742,
       0.16904154, 0.79904293, 0.81789994, 0.60878832, 0.65088801,
       0.16158691, 0.54796056, 0.59367186, 0.84146387, 0.26399374,
       0.48867497, 0.3985106 , 0.91770037, 0.72452809, 0.54450468,
       0.46451576, 0.95457031, 0.54614819, 0.88685306, 0.84905152])

In [26]:
wgo

array([[0.784717  , 0.6736477 , 0.71002377, 0.4353708 ],
       [0.78595262, 0.67129969, 0.21427314, 0.95495082],
       [0.10258804, 0.5949998 , 0.31759486, 0.59171532],
       [0.63254126, 0.45370328, 0.15369687, 0.95188547],
       [0.88900752, 0.18531463, 0.89293612, 0.79554553],
       [0.83341817, 0.88561499, 0.35066831, 0.25886431],
       [0.45455053, 0.4280099 , 0.26766644, 0.85427973],
       [0.96475377, 0.18799556, 0.24812203, 0.63500553],
       [0.77283348, 0.84511277, 0.56751952, 0.97212645],
       [0.09765768, 0.23249729, 0.27422042, 0.59100742],
       [0.82879547, 0.88484241, 0.45618835, 0.73179029],
       [0.66266337, 0.46958084, 0.31610151, 0.2725047 ],
       [0.96932896, 0.59396296, 0.79556849, 0.246791  ],
       [0.56857192, 0.34569481, 0.15619611, 0.08407749],
       [0.46263756, 0.19515572, 0.0048602 , 0.38641118],
       [0.50834485, 0.95753061, 0.4605764 , 0.99141466],
       [0.61077073, 0.19917859, 0.91612689, 0.90961545],
       [0.8135778 , 0.5689999 ,

In [27]:
bo

array([0.90394225, 0.66935081, 0.28119723, 0.34684264])

In [28]:
cost=[]

In [29]:
for epoch in range(500001):  

    zh = np.dot(features, wgh) + bh
    ah = sigmoid(zh)

    zo = np.dot(ah, wgo) + bo
    ao = softmax(zo)



    dcost_dzo = ao - cont_labels
    dzo_dwo = ah

    dcost_wo = np.dot(dzo_dwo.T, dcost_dzo)

    dcost_bo = dcost_dzo


    dzo_dah = wgo
    dcost_dah = np.dot(dcost_dzo , dzo_dah.T)
    dah_dzh = sigmoid_derivative(zh)
    dzh_dwh = features
    dcost_wh = np.dot(dzh_dwh.T, dah_dzh * dcost_dah)

    dcost_bh = dcost_dah * dah_dzh


    wgh -= alpha * dcost_wh
    bh -= alpha * dcost_bh.sum(axis=0)

    wgo -= alpha * dcost_wo
    bo -= alpha * dcost_bo.sum(axis=0)

    if epoch % 50000 == 0:
        loss = np.sum(-cont_labels * np.log(ao))
        print(f'Loss after {epoch} no of epochs:', loss)
        cost.append(loss)

Loss after 0 no of epochs: 64.43674872256742
Loss after 50000 no of epochs: 28.151091840344847
Loss after 100000 no of epochs: 5.207449158092061
Loss after 150000 no of epochs: 0.9160651693854673
Loss after 200000 no of epochs: 0.4400677831513487
Loss after 250000 no of epochs: 0.29361837655918555
Loss after 300000 no of epochs: 0.22023005667764928
Loss after 350000 no of epochs: 0.17593647962827386
Loss after 400000 no of epochs: 0.14625646034958345
Loss after 450000 no of epochs: 0.12497518870452429
Loss after 500000 no of epochs: 0.10897222069030474


In [30]:
#So,we now have the correct updated weights
#Now,we use these weights and perform a forward 
#pass through the input we wish to

In [37]:
def predict(x):
    predictions = []
    final_pred=[]
  
    zh = np.dot(x, wgh) + bh
    ah = sigmoid(zh)

    zo = np.dot(ah, wgo) + bo
    ao = softmax(zo)
    
    for i in range(len(ao)):
        predictions.append(np.argmax(ao[i], axis=0))
        temp=dec2bin(np.argmax(ao[i],axis=0))
        final_pred.append(temp)
    return final_pred
    #return predictions

In [38]:
predict(features)

['00',
 '01',
 '10',
 '11',
 '01',
 '00',
 '11',
 '10',
 '10',
 '11',
 '00',
 '01',
 '11',
 '10',
 '01',
 '00',
 '11',
 '10',
 '01',
 '00',
 '10',
 '11',
 '00',
 '01',
 '01',
 '00',
 '11',
 '10',
 '00',
 '01',
 '10',
 '11']